on: [push, workflow_dispatch]

name: test

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install
        working-directory: .
        run: yarn install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run local tests
        working-directory: .
        run: yarn test &&  forge coverage --no-match-test Mainnet --report lcov
      - name: Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: './lcov.info'
          min_coverage: 95
          exclude: 'test/* test/resources/* archive/* script/*'
      - name: Run snapshot
        working-directory: .
        run: forge snapshot --no-match-test Mainnet
      - name: Run mainnet tests
        working-directory: .
        run: forge test --match-test Mainnet --fork-url {{ secrets.MAINNET_RPC_URL }}
