name: scanERC2771ForMsgSender

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: test "$(grep msg.sender contracts/Token.sol contracts/ContinuousFundraising.sol |wc -l)" -eq 0 |
      test "$(grep msg.data contracts/Token.sol contracts/ContinuousFundraising.sol |wc -l)" -eq 0

      # these two contracts inherit from ERC2771Context and may not contain msg.sender or msg.data. Instead, they must use _msgSender() and _msgData()
